[2024-11-07T08:59:22.695-1100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-07T08:59:22.712-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_transform_clean_data.remove_duplicates scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T08:59:22.722-1100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_transform_clean_data.remove_duplicates scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2024-11-07T08:59:22.722-1100] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-07T08:59:22.740-1100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): remove_duplicates> on 2024-11-06 00:00:00+00:00
[2024-11-07T08:59:22.752-1100] {standard_task_runner.py:72} INFO - Started process 318041 to run task
[2024-11-07T08:59:22.759-1100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'extract_transform_clean_data', 'remove_duplicates', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/extract_transform_clean_data.py', '--cfg-path', '/tmp/tmpi15epr1k']
[2024-11-07T08:59:22.761-1100] {standard_task_runner.py:105} INFO - Job 13: Subtask remove_duplicates
[2024-11-07T08:59:22.829-1100] {task_command.py:467} INFO - Running <TaskInstance: extract_transform_clean_data.remove_duplicates scheduled__2024-11-06T00:00:00+00:00 [running]> on host debian
[2024-11-07T08:59:24.332-1100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='extract_transform_clean_data' AIRFLOW_CTX_TASK_ID='remove_duplicates' AIRFLOW_CTX_EXECUTION_DATE='2024-11-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-06T00:00:00+00:00'
[2024-11-07T08:59:24.334-1100] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-07T08:59:24.334-1100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-07T08:59:24.334-1100] {logging_mixin.py:190} INFO - Current task name:remove_duplicates state:running start_date:2024-11-07 19:59:22.712956+00:00
[2024-11-07T08:59:24.335-1100] {logging_mixin.py:190} INFO - Dag name:extract_transform_clean_data and current dag run status:running
[2024-11-07T08:59:24.335-1100] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-07T08:59:24.336-1100] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/airflow/dags/extract_transform_clean_data.py", line 77, in remove_duplicates
    df = df.drop_duplicates()  # Remove duplicate rows
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'drop_duplicates'
[2024-11-07T08:59:24.347-1100] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-07T08:59:24.347-1100] {logging_mixin.py:190} INFO - Task start:2024-11-07 19:59:22.712956+00:00 end:2024-11-07 19:59:24.346442+00:00 duration:1.633486
[2024-11-07T08:59:24.347-1100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): remove_duplicates> dag:<DAG: extract_transform_clean_data> dagrun:<DagRun extract_transform_clean_data @ 2024-11-06 00:00:00+00:00: scheduled__2024-11-06T00:00:00+00:00, state:running, queued_at: 2024-11-07 19:58:08.919572+00:00. externally triggered: False>
[2024-11-07T08:59:24.348-1100] {logging_mixin.py:190} INFO - Failure caused by 'str' object has no attribute 'drop_duplicates'
[2024-11-07T08:59:24.348-1100] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_transform_clean_data, task_id=remove_duplicates, run_id=scheduled__2024-11-06T00:00:00+00:00, execution_date=20241106T000000, start_date=20241107T195922, end_date=20241107T195924
[2024-11-07T08:59:24.369-1100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-07T08:59:24.370-1100] {standard_task_runner.py:124} ERROR - Failed to execute job 13 for task remove_duplicates ('str' object has no attribute 'drop_duplicates'; 318041)
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouaillaamiri/Development/lsi_3/airflow/airflow/dags/extract_transform_clean_data.py", line 77, in remove_duplicates
    df = df.drop_duplicates()  # Remove duplicate rows
         ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'drop_duplicates'
[2024-11-07T08:59:24.457-1100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-07T08:59:24.501-1100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-07T08:59:24.503-1100] {local_task_job_runner.py:245} INFO - ::endgroup::
