[2024-11-06T10:53:31.348-1100] {processor.py:186} INFO - Started process (PID=219333) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:53:31.350-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:53:31.356-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:53:31.355-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:53:31.364-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:53:31.362-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:53:31.365-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:53:31.365-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:53:31.366-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:53:31.436-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-11-06T10:54:01.589-1100] {processor.py:186} INFO - Started process (PID=220059) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:01.591-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:54:01.594-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:01.594-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:01.602-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:01.600-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:54:01.602-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:01.602-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:54:01.603-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:01.653-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-06T10:54:32.312-1100] {processor.py:186} INFO - Started process (PID=220584) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:32.314-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:54:32.317-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:32.317-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:32.324-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:32.322-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:54:32.324-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:54:32.324-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:54:32.324-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:54:32.365-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.062 seconds
[2024-11-06T10:55:03.064-1100] {processor.py:186} INFO - Started process (PID=221024) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:03.065-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:55:03.069-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:03.069-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:03.077-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:03.075-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:55:03.077-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:03.077-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:55:03.078-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:03.129-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.076 seconds
[2024-11-06T10:55:33.901-1100] {processor.py:186} INFO - Started process (PID=221651) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:33.903-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:55:33.909-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:33.908-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:33.919-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:33.917-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:55:33.920-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:55:33.919-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:55:33.920-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:55:33.971-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.087 seconds
[2024-11-06T10:56:04.266-1100] {processor.py:186} INFO - Started process (PID=222027) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:04.268-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:56:04.271-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:04.271-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:04.277-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:04.276-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:56:04.278-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:04.278-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:56:04.278-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:04.322-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.067 seconds
[2024-11-06T10:56:44.369-1100] {processor.py:186} INFO - Started process (PID=223108) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:44.371-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:56:44.376-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:44.375-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:44.383-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:44.382-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:56:44.383-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:56:44.383-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:56:44.384-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:56:44.430-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-06T10:57:15.379-1100] {processor.py:186} INFO - Started process (PID=224265) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:15.382-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:57:15.386-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:15.385-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:15.392-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:15.391-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:57:15.393-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:15.393-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:57:15.393-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:15.440-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2024-11-06T10:57:45.880-1100] {processor.py:186} INFO - Started process (PID=224973) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:45.890-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:57:45.907-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:45.899-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:45.918-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:45.916-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:57:45.920-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:57:45.920-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:57:45.922-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:57:46.009-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.147 seconds
[2024-11-06T10:58:16.962-1100] {processor.py:186} INFO - Started process (PID=225675) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:16.964-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:58:16.967-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:16.967-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:16.972-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:16.971-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:58:16.972-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:16.972-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:58:16.973-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:17.021-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.068 seconds
[2024-11-06T10:58:47.723-1100] {processor.py:186} INFO - Started process (PID=226393) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:47.725-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:58:47.730-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:47.729-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:47.738-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:47.736-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:58:47.739-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:58:47.738-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:58:47.740-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:58:47.802-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.094 seconds
[2024-11-06T10:59:18.108-1100] {processor.py:186} INFO - Started process (PID=227101) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:18.110-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:59:18.117-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:18.116-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:18.126-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:18.124-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:59:18.127-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:18.126-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:59:18.127-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:18.182-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2024-11-06T10:59:48.368-1100] {processor.py:186} INFO - Started process (PID=227489) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:48.370-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T10:59:48.373-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:48.373-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:48.379-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:48.378-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T10:59:48.379-1100] {logging_mixin.py:190} INFO - [2024-11-06T10:59:48.379-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T10:59:48.380-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T10:59:48.434-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-06T11:00:56.011-1100] {processor.py:186} INFO - Started process (PID=228674) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:00:56.013-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:00:56.018-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:00:56.017-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:00:56.024-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:00:56.023-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:00:56.025-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:00:56.025-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:00:56.026-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:00:56.082-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-11-06T11:01:26.549-1100] {processor.py:186} INFO - Started process (PID=229275) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:26.553-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:01:26.558-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:26.558-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:26.565-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:26.564-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:01:26.566-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:26.566-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:01:26.567-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:26.624-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-11-06T11:01:56.908-1100] {processor.py:186} INFO - Started process (PID=229648) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:56.909-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:01:56.913-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:56.912-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:56.918-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:56.917-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:01:56.919-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:01:56.919-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:01:56.920-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:01:56.971-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.075 seconds
[2024-11-06T11:02:27.599-1100] {processor.py:186} INFO - Started process (PID=230240) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:27.601-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:02:27.605-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:27.605-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:27.611-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:27.609-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:02:27.612-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:27.611-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:02:27.612-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:27.660-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.071 seconds
[2024-11-06T11:02:58.387-1100] {processor.py:186} INFO - Started process (PID=231228) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:58.392-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:02:58.396-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:58.395-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:58.402-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:58.401-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:02:58.403-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:02:58.403-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:02:58.404-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:02:58.454-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-11-06T11:03:28.988-1100] {processor.py:186} INFO - Started process (PID=231587) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:28.991-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:03:28.996-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:28.995-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:29.003-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:29.001-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:03:29.004-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:29.003-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:03:29.005-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:29.066-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2024-11-06T11:03:59.504-1100] {processor.py:186} INFO - Started process (PID=232264) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:59.505-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:03:59.509-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:59.508-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:59.514-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:59.513-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:03:59.515-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:03:59.514-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:03:59.515-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:03:59.559-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-11-06T11:04:30.264-1100] {processor.py:186} INFO - Started process (PID=232636) to work on /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:04:30.267-1100] {processor.py:914} INFO - Processing file /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-11-06T11:04:30.272-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:04:30.272-1100] {dagbag.py:588} INFO - Filling up the DagBag from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:04:30.279-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:04:30.278-1100] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-11-06T11:04:30.280-1100] {logging_mixin.py:190} INFO - [2024-11-06T11:04:30.280-1100] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-11-06T11:04:30.281-1100] {processor.py:927} WARNING - No viable dags retrieved from /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-11-06T11:04:30.360-1100] {processor.py:208} INFO - Processing /home/ouaillaamiri/Development/lsi_3/airflow/venv/lib/python3.11/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
